name: GitHub Action for API Registry
description: version, release, governanace, contract, performance, tests and privacy
author: PerfAI, Inc.
branding:
  icon: "package"
  color: "gray-dark"
 # icon: trending-up
 # color: red
      
inputs:
  perfai-hostname:
    description: 'Hostname of API-Privacy'
    required: true
  perfai-username:
    description: 'Username of API-Privacy'
    required: true
  perfai-password:
    description: 'Password of API-Privacy'
    required: true
  openapi_spec:
    description: 'URL of API-Privacy'
    required: true
  governance_email:
    description: 'email of API-Privacy'
    required: true   
  name:
    description: 'OpenAPI-Specification/Swagger URL'
    required: true
  source:
    description: 'API Base Path'
    required: true
  version:
    description: 'Token Authentication URL'
    required: true
    
outputs:
  report:
    description: Displays Report

runs:
  using: "composite"
  steps:
    - name: Grant execute permission for api_registry.sh
      run: chmod +x ${GITHUB_ACTION_PATH}/api_registry.sh
      shell: bash
      
    - name: Run api_registry.sh
      run: |
        ${GITHUB_ACTION_PATH}/api_registry.sh --hostname "${{ inputs.perfai-hostname }}" --username "${{ inputs.perfai-username }}" --password "${{ inputs.perfai-password }}" --openapi_spec "${{ inputs.perfai-openapi_spec }}" --governance_email "${{ inputs.perfai-governance_email }}" --version "${{ inputs.perfai-version }}" --name "${{ inputs.perfai-name }}" --source "${{ inputs.perfai-source }}"
      shell: bash


### THIS IS 2nd SCRIPT (ACTION-RUN.SH) ###
    - name: Grant execute permission for action-run.sh
      run: chmod +x ${GITHUB_ACTION_PATH}/action-run.sh
      shell: bash
      
    - name: Run action-run.sh
      run: |
        ${GITHUB_ACTION_PATH}/action-run.sh --hostname "${{ inputs.perfai-hostname }}" --username "${{ inputs.perfai-username }}" --password "${{ inputs.perfai-password }}" --openapi_spec "${{ inputs.perfai-openapi_spec }}" --governance_email "${{ inputs.perfai-governance_email }}" --version "${{ inputs.perfai-version }}" --name "${{ inputs.perfai-name }}" --source "${{ inputs.perfai-source }}"
      shell: bash
