name: GitHub Action for AI Running
description: API Privacy and API Governance
author: PerfAI, Inc.
branding:
  icon: "package"
  color: "gray-dark"
      
inputs:
  perfai-username:
    description: 'Username of API-Privacy'
    required: true
  perfai-password:
    description: 'Password of API-Privacy'
    required: true
  perfai-catalog-id:
    description: 'Catalog Id need to Provide'
    required: true
  perfai-wait-for-completion:
    description: 'True or False'
    required: true   

runs:
  using: "composite"
  steps:
    - name: Grant execute permission for action-run.sh
      run: chmod +x ${GITHUB_ACTION_PATH}/action-run.sh
      shell: bash
      
    - name: Run action-run.sh
      run: |
        ${GITHUB_ACTION_PATH}/action-run.sh --username "${{ inputs.perfai-username }}" --password "${{ inputs.perfai-password }}" --catalog-id "${{ inputs.perfai-catalog-id }}" --wait-for-completion "${{ inputs.perfai-wait-for-completion }}"
      shell: bash
