name: GitHub Action for APIContract
description: version, release, governanace, contract, performance, tests and privacy
author: PerfAI, Inc.
branding:
  icon: "package"
  color: "gray-dark"
 # icon: trending-up
 # color: red
      
inputs:
  perfai-username:
    description: 'Username of API-Contract'
    required: true
  perfai-password:
    description: 'Password of API-Contract'
    required: true
  perfai-apiSpecURL:
    description: OpenAPI-Specification/Swagger URL
    required: true
  perfai-apiBasePath:
    description: API Base Path
    required: true
  perfai-authUrl:
    description: Token Authentication URL
    required: true
  perfai-authBody:
    description: Authentication Body JSON/Data
    required: true
  perfai-authHeaders:
    description: Authentication Headers
  perfai-licenseKey:
    description: A code or token that allows the user to identify him/herself as a legal customer 
    required: false
  perfai-governance_email:
    description: 'Email id that send report' 
    required: false

    
outputs:
  report:
    description: Displays performance report

runs:
  using: "composite"
  steps:
    - run: ${GITHUB_ACTION_PATH}/perfai-run-scan.sh --username "${{inputs.perfai-username}}" --password "${{ inputs.perfai-password }}" --apiSpecURL "${{ inputs.perfai-apiSpecURL }}" --authUrl "${{ inputs.perfai-authUrl }}" --authBody "${{ inputs.perfai-authBody }}" --authHeaders  "${{ inputs.perfai-authHeaders}}" --licenseKey "${{ inputs.perfai-licenseKey }}" --governance_email "${{ inputs.perfai-governance_email }}"
    # - run: docker run --rm -e apiSpecURL=${{ inputs.apiSpecURL }} -e apiBasePath=${{ inputs.apiBasePath }} -e authUrl=${{ inputs.authUrl }} -e authBody=${{ inputs.authBody }} -e authHeaders=${{ inputs.authHeaders }} -e licenseKey=${{ inputs.licenseKey }} -v ${{ github.workspace }}/.github:/app/.github ghcr.io/perfai-inc/perfai-engine:main
      shell: bash
