name: APIContract Scan
description: version, release, governanace, contract, performance, tests and privacy
author: PerfAI, Inc.
branding:
  icon: "package"
  color: "gray-dark"
 # icon: trending-up
 # color: red
      
inputs:
  apiSpecURL:
    description: OpenAPI-Specification/Swagger URL
    required: true
  apiBasePath:
    description: API Base Path
    required: true
  authUrl:
    description: Token Authentication URL
    required: true
  authBody:
    description: Authentication Body JSON/Data
    required: true
  authHeaders:
    description: Authentication Headers
  licenseKey:
    description: A code or token that allows the user to identify him/herself as a legal customer 
    required: false
    
outputs:
  report:
    description: Displays performance report

runs:
  using: "composite"
  steps:
    - run: ${GITHUB_ACTION_PATH}/perfai-run-scan.sh --username "${{inputs.apisec-username}}" --password "${{ inputs.apisec-password }}" --apiSpecURL "${{ inputs.apisec-apiSpecURL }}" --authUrl "${{ inputs.apisec-authUrl }}" --authBody "${{ inputs.apisec-authBody }}" --authHeaders  "${{ inputs.authHeaders}}" --licenseKey "${{ inputs.licenseKey }}" --governance_email "${{ inputs.governance_email }}"
    # - run: docker run --rm -e apiSpecURL=${{ inputs.apiSpecURL }} -e apiBasePath=${{ inputs.apiBasePath }} -e authUrl=${{ inputs.authUrl }} -e authBody=${{ inputs.authBody }} -e authHeaders=${{ inputs.authHeaders }} -e licenseKey=${{ inputs.licenseKey }} -v ${{ github.workspace }}/.github:/app/.github ghcr.io/perfai-inc/perfai-engine:main
      shell: bash
