name: GitHub Action for API Registry
description: version, release, governanace, contract, performance, tests and privacy
author: PerfAI, Inc.
branding:
  icon: "package"
  color: "gray-dark"
 # icon: trending-up
 # color: red
      
inputs:
  perfai-hostname:
    description: 'Hostname of API-Privacy'
    required: true
  perfai-username:
    description: 'Username of API-Privacy'
    required: true
  perfai-password:
    description: 'Password of API-Privacy'
    required: true
  openapi_spec:
    description: 'URL of API-Privacy'
    required: true
  governance_email:
    description: 'email of API-Privacy'
    required: true   
  name:
    description: 'OpenAPI-Specification/Swagger URL'
    required: true
  source:
    description: API Base Path
    required: true
  version:
    description: Token Authentication URL
    required: true
  client_id:
    description: 'The Client ID'
    required: true
  client_secret:
    description: 'The Client Secret'
    required: true  
    
outputs:
  report:
    description: Displays performance report

runs:
  using: "composite"
  steps:
    - run: ${GITHUB_ACTION_PATH}/m2m.sh --hostname "${{inputs.perfai-hostname}}" --username "${{inputs.perfai-username}}" --password "${{ inputs.perfai-password }}" --openapi_spec "${{ inputs.openapi_spec }}" --governance_email "${{ inputs.governance_email }}" --name "${{ inputs.name }}" --source  "${{ inputs.source}}" --version "${{ inputs.version }}" --client_secret "${{ inputs.client_secret }}" --client_id "${{ inputs.client_id }}"
      shell: bash
      env:
        CLIENT_ID: ${{ secrets.client_id }}
        CLIENT_SECRET: ${{ secrets.client_secret }}
