name: PerfAI APIPrivacy Test
description: PerfAI API Privacy Test as part of your GitHub Actions workflow.
author: PerfAI, Inc.
branding:
  icon: "package"
  color: "gray-dark"
      
inputs:
  perfai-username:
    description: 'API Privacy Username'
    required: true
  perfai-password:
    description: 'API Privacy Password'
    required: true
  perfai-api-id:
    description: 'API Id generated for the API in API Privacy'
    required: true
  perfai-api-name:
    description: 'API name/label'
    required: true
  perfai-wait-for-completion:
    description: 'To wait till the tests gets completed, set to `true` '
    required: false
    default: "false"
  perfai-fail-on-new-leaks:
    description: 'To fail the build on new leaks introduced with this commit, set to `true`.'
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Grant execute permission for action-run.sh
      run: chmod +x ${GITHUB_ACTION_PATH}/action-run.sh
      shell: bash
      
    - name: Run action-run.sh
      run: |
        ${GITHUB_ACTION_PATH}/action-run.sh --username "${{ inputs.perfai-username }}" --password "${{ inputs.perfai-password }}" --catalog-id "${{ inputs.perfai-api-id }}" --wait-for-completion "${{ inputs.perfai-wait-for-completion }}" --fail-on-new-leaks "${{ inputs.perfai-fail-on-new-leaks}}"
      shell: bash
