name: GitHub Action for API Privacy
description: API Privacy Action RUN 
author: PerfAI, Inc.
branding:
  icon: "package"
  color: "gray-dark"
      
inputs:
  perfai-hostname:
    description: 'Hostname of API-Privacy'
    required: true
  perfai-username:
    description: 'Username of API-Privacy'
    required: true
  perfai-password:
    description: 'Password of API-Privacy'
    required: true


runs:
  using: "composite"
  steps:
    - name: Grant execute permission for action-run.sh
      run: chmod +x ${GITHUB_ACTION_PATH}/action-run.sh
      shell: bash
      
    - name: Run action-run.sh
      run: |
        ${GITHUB_ACTION_PATH}/action-run.sh --hostname "${{ inputs.perfai-hostname }}" --username "${{ inputs.perfai-username }}" --password "${{ inputs.perfai-password }}"
      shell: bash
