name: AI Running
on:
  push:
    branches: [ "main" ]
  # schedule:
  #    - cron: '*/5 * * * *'
            

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Github Action for Action-Run
        uses: PerfAI-Inc/Github-Action-CI-CD@v1.2.2
        with:
           perfai-username: ${{ secrets.perfai_username }}
           perfai-password: ${{ secrets.perfai_password }}
           perfai-catalog-id: "66e1a3ddf39d139dca94ee13"
           perfai-wait-for-completion: "true"


          
