name: Action-Run
on:
  push:
    branches: [ "main" ]
  # schedule:
  #    - cron: '*/5 * * * *'
            

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Github Action for Action-Run
        uses: PerfAI-Inc/Github-Action-CI-CD@v1.2.1
        with:
           perfai-hostname: https://app.apiprivacy.com/
           perfai-username: ${{ secrets.perfai_username }}
           perfai-password: ${{ secrets.perfai_password }}
           


          
