# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "main" ]
  # schedule:
  #   - cron: '45 15 * * 4'


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Github Action for API Registry
        uses: PerfAI-Inc/Github-Action-CI-CD@v28.0
        with:
           perfai-hostname: https://app.apiprivacy.com/
           perfai-username: ${{ secrets.perfai_username }}
           perfai-password: ${{ secrets.perfai_password }}
           sarif-result-file: "perfai-results.sarif"

           
      - name: PerfAI Sarif
        id: read-file
        run: |
          cat perfai-results.sarif

      # - name: wget
      #   uses: wei/wget@v1
      #   with:           
      #      args: -O simple-example.sarif https://raw.githubusercontent.com/microsoft/sarif-tutorials/main/samples/1-Introduction/simple-example.sarif  
           
    ### Upload Sarif File ### 
      # - name: upload sarif file to repository
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif-file: ./perfai-results.sarif

      # - name: Run npm install
      #   run: npm install

      # - name: Run ESLint
      #   run: node_modules/.bin/eslint build docs lib script spec-main -f node_modules/@microsoft/eslint-formatter-sarif/sarif.js -o perfai-results.sarif || true

      - name: Generate SARIF file
        run: |
           echo '{
           "version": "2.1.0",
           "runs": [
             {
              "tool": {
                "driver": {
                  "name": "Custom PII Scanner",
                  "version": "1.0.0",
                  "informationUri": "https://example.com",
                  "rules": []
                }
              },
              "results": [
                {
                  "ruleId": "PII-Leak",
                  "message": {
                    "text": "PII data leak detected in the response."
                  },
                  "locations": [
                    {
                      "physicalLocation": {
                        "artifactLocation": {
                          "uri": "/user/{username}"
                        },
                        "region": {
                          "startLine": 1
                        }
                      }
                    }
                  ],
                  "properties": {
                    "id": "66b357212f900c785d28206a",
                    "impact": "Leak",
                    "location": "Response Field.username",
                    "name": "username",
                    "label": "PII Data",
                    "direction": "OUT",
                    "severity": "Medium",
                    "created_on": "2024-08-10T09:30:27.739Z",
                    "response": "{\"id\":1,\"username\":\"johnsmith\",\"firstName\":\"John\",\"lastName\":\"Smith\",\"email\":\"john@example.com\",\"password\":\"s3cur3p@ssw0rd\",\"phone\":\"1234567890\",\"userStatus\":5}",
                    "explainer": "PII Data includes personally identifiable information used for online identification, such as names, addresses, and contact details.",
                    "remediation": "Encrypt sensitive PII data during storage and transmission to prevent unauthorized access. Implement masking or partial obfuscation techniques where feasible."
                  }
                }
               ]
              }
             ]
           }' > perfai-results.sarif
        
           
      - name: Validate SARIF file
        run: |
          if ! jq . perfai-results.sarif > /dev/null 2>&1; then
            echo "SARIF file is not valid."
            exit 1
          fi


    ### Upload Sarif File ### 
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: ./perfai-results.sarif
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          # category: my-analysis-tool
 
          
    # ### Email Alert Notifcation ###  
    #   - name: Send mail
    #     if: failure()
    #     uses: dawidd6/action-send-mail@v3
    #     with:
    #        server_address: smtp.gmail.com
    #        server_port: 465
    #        username: ${{ secrets.EMAIL_USERNAME }}
    #        password: ${{ secrets.EMAIL_PASSWORD }}
    #        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}  
    #        body: Build job of ${{ github.workflow }} https://github.com/PerfAI-Inc/Github-Action-CI-CD/security/code-scanning          
    #        to: rashid@perfai.ai
    #        from: Github Action 
    #        convert_markdown: true
    #        attachments: attachments.zip,git.diff,./dist/static/*.js   





          
