# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "main" ]
  # schedule:
  #   - cron: '45 15 * * 4'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Github Action for API Registry
        uses: PerfAI-Inc/Github-Action-CI-CD@v25.0
        with:
           perfai-hostname: https://app.apiprivacy.com/
           perfai-username: ${{ secrets.perfai_username }}
           perfai-password: ${{ secrets.perfai_password }}
           sarif-result-file: "perfai-results.sarif"
           
    
    ### Upload Sarif File ### 
      # - name: upload sarif file to repository
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif-result-file: ./perfai-results.sarif


      - name: Checkout repository
        uses: actions/checkout@v4
      
    ### Upload Sarif File ### 
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif-result-file: perfai-results.sarif
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          category: my-analysis-tool

          
    # ### Email Alert Notifcation ###  
    #   - name: Send mail
    #     if: failure()
    #     uses: dawidd6/action-send-mail@v3
    #     with:
    #        server_address: smtp.gmail.com
    #        server_port: 465
    #        username: ${{ secrets.EMAIL_USERNAME }}
    #        password: ${{ secrets.EMAIL_PASSWORD }}
    #        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}  
    #        body: Build job of ${{ github.workflow }} https://github.com/PerfAI-Inc/Github-Action-CI-CD/security/code-scanning          
    #        to: rashid@perfai.ai
    #        from: Github Action 
    #        convert_markdown: true
    #        attachments: attachments.zip,git.diff,./dist/static/*.js   





          
